spring:
  datasource:
    url: jdbc:mysql://localhost/pse_development?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 69h97jnv

  jpa:
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext

